wirenboard/wb-configs

debian/changelog, debian/control, debian/wb-configs-stretch.postinst, debian/wb-configs.postinst, debian/wb-configs.preinst, debian/wb-configs.undisplace
An error caused by moving ssh configuration from wb-configs to wb-configs-stretch without preparation scripts. It breaks update from wb-configs < 1.75.4.
Now we need to use some magic copied from config-package-dev helpers to remove diversion of ssh config from wb-configs < 1.75.4 before configuring wb-configs-stretch. It is done both in preinst of wb-configs and postinst wb-configs-stretch just in case. The update procedure preserves user changed configuration.
Tested upgrade from 1.75.3 (with original and user modified configs) and from 1.77 (ignores procedure).
=> Fix sshd diversion clash on upgrade from wb-configs < 1.75.4

debian/changelog, debian/wb-configs.postinst
Error in 'journalctl' before change:
Feb 04 23:20:30 wb wb-init[2454]: Starting board-specific initscript: wb-initCannot parse config file '/etc/fw_env.config': No such file or directory
Feb 04 23:20:30 wb wb-init[2454]: Error: environment not initialized
Feb 04 23:20:31 wb wb-init[2454]: Cannot parse config file '/etc/fw_env.config': No such file or directory
Feb 04 23:20:31 wb wb-init[2454]: Error: environment not initialized
Feb 04 23:20:31 wb wb-init[2454]: .
Before fix:
Setting up wb-configs (1.79) ...
/var/lib/dpkg/info/wb-configs.postinst: line 10: FVER: command not found
cp: cannot stat '/usr/share/wb-configs/u-boot/default.': No such file or directory
*** OMINOUS WARNING ***: /etc/hostname is not linked to either hostname.wb or hostname.wb-orig
*** OMINOUS WARNING ***: …
=> Post install scipt fails on WB5

configs/root/.bashrc.wb, debian/changelog
Применяется последним и затирает всё, что прописывали в /etc/profile.d/...
=> .bashrc appending to $PYTHONPATH instead of rewriting it

configs-stretch/etc/apt/sources.list.d/debian-upstream.list, debian/changelog, debian/wb-configs-stretch.postinst
```
root@wirenboard-AQZBLNTY:~# cat /etc/apt/sources.list
deb http://mirror.yandex.ru/debian/ stretch main
deb http://mirror.yandex.ru/debian/ stretch-updates main
deb http://security.debian.org stretch/updates main
root@wirenboard-AQZBLNTY:~# apt update
Ign:1 http://mirror.yandex.ru/debian stretch InRelease
Hit:2 http://security.debian.org stretch/updates InRelease      
Hit:3 http://releases.contactless.ru/stable/stretch stretch InRelease          
Hit:4 http://mirror.yandex.ru/debian stretch-updates InRelease                 
Hit:5 http://mirror.yandex.ru/debian stretch Release                           
Hit:6 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can …
```
=> change upstream debian repository location on stretch

configs-stretch/etc/logrotate.d/messages, configs-stretch/etc/watchdog.conf.wb, debian/changelog, debian/control, debian/wb-configs-stretch.postinst, debian/wb-configs.postinst
apt dist-upgrade can fail because of watchdog. apt removes busybox-syslogd but watchdog is not notifyed about it, so it can reset device. We support both busybox-syslogd and rsyslog in configs, so one can install rsyslog manually after dist-upgrade.
=> rsyslog does not replace busybox-syslogd automaticaly

debian/changelog, debian/control
This can deal with wb-mqtt-gpio or some other packages removals while moving to the new repo (https://wirenboard.bitrix24.ru/company/personal/user/28/tasks/task/view/38030/)
=> add wb-suite to recommends

configs/etc/nginx/sites-available/default.wb, debian/changelog, debian/wb-configs.postinst
К сожалению, тем, у кого браузер решил, что index.html можно показывать из кэша, надо будет один раз Ctrl+Shift+r нажать. Потом уже будут действовать настройки из Cache-Control.
=> Disable client side caching of index.html

configs/etc/wb-configs.d/01wb-configs, debian/changelog
It is the reason why Wi-Fi AP may not start properly on WB7 sometimes.
This fixes failing Wi-Fi AP mode on WB7.
=> fix race condition on /etc/network/interfaces during boot

debian/changelog, debian/control, debian/wb-configs-stretch.postinst
* add wb-configs-stretch pre-dependency on wb-update-manager
* remove transitional repo settings on successful wb-release invokation.
These changes should improve stability of upgrade from legacy repository
=> more careful upgrade from legacy repository

configs/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf, debian/changelog
Тянется из #57, там не совсем правильно был написан `override.conf` для сервиса `serial-getty@ttyS0.service`. systemd ругался на две директивы `ExecStart`. В примере по ссылке в описании коммита (https://github.com/systemd/systemd/issues/15611) в `override.conf` сначала надо было написать `ExecStart=`, чтобы сбросить старое значение. После этого логин через консоль у меня заработал.
=> fix broken debug console login on Wiren Board 7

configs/etc/apt/preferences.d/50backports, debian/changelog
Этих пинов не хватает для того, чтобы установить build-deps при сборке, и обычные зависимости на контроллере
=> add apt pin to install modemmanager dependencies from backports

configs/etc/update-motd.d/20-wirenboard-sysinfo, debian/changelog
Adopted from https://github.com/armbian/build/blob/master/packages/bsp/common/etc/update-motd.d/30-armbian-sysinfo
=> Add motd banner with system information

configs/etc/fstab.wb, debian/changelog
https://wirenboard.com/wiki/Wiren_Board_7#%D0%A1%D0%BB%D0%BE%D1%82_MicroSD
Монтируем только первый раздел для простоты (в большинстве случаев он один), чтобы не тянуть новые зависимости (udisks2 и пр).
=> Auto-mount MicroSD to /mnt/sdcard

configs/usr/lib/NetworkManager/conf.d/wb.conf, debian/changelog, debian/control
Для того, чтобы сеть при этом не ломалась, требуется ядро с правками в драйвере (не старше 5.10.35-wb127)
=> enable wlan1 in NetworkManager

configs/etc/ppp/ip-up.d/0000usepeerdns.wb, configs/etc/udev/rules.d/99-wb-modem.rules, configs/usr/lib/NetworkManager/conf.d/wb.conf, debian/changelog, debian/wb-configs.displace
- backport ppp ip-up.d script from Debian bookworm (can't backport the whole package because of dependencies on libssl3 and newer libc) to fix resolv.conf rewriting by PPP (breaks DNS resolving when modem connection is up)
- allow `usb0` interface in NetworkManager (was denied previously to keep internal modem RNDIS untouched). Internal modem is marked as unmanaged in udev. Now external RNDIS devices (e.g. Android phones as USB modems) work out of the box.
=> Manage external USB RNDIS via NetworkManager + fix PPP breaking resolv.conf

configs/lib/systemd/system/ModemManager.service.d/override.conf, configs/usr/lib/wb-configs/detect_legacy_modem_config.sh, debian/changelog
- немного ускоряет загрузку контроллера, поскольку ModemManager не запускается почём зря
- не даёт случиться драке между pppd и ModemManager при сохранении конфига сети через web-интерфейс
=> Disable ModemManager if ppp is configured in interfaces

configs/usr/lib/cgi-bin/fwupdate_upload.py, debian/changelog
Не ломает обратную совместимость, но даёт поддержку новым скриптам из wb-utils менять директорию назначения для загружаемых FIT-файлов (для схемы с одним rootfs файл надо будет загружать в `/mnt/data`)
=> fwupdate_upload: single rootfs update scheme support

configs/etc/apt/preferences.d/40wb-experimental, debian/changelog
Связано с багом в wbci, из-за которого в testing set-ы добавляется пакет wb-release-info, из-за которого может испортиться `/etc/apt/sources.list.d/wirenboard.list` при сборке rootfs (там останется только этот testing set, основной репозиторий удалится)
=> forbid wb-release-info installation from testing sets

configs/usr/lib/cgi-bin/fwupdate_upload.py, debian/changelog
* fwupdate_upload: use dir defined by wb-watch-update if it exists
* fwupdate_upload: fix python formatting
Backport of #108
=> fwupdate_upload: single rootfs update scheme support (#108)

configs-stretch/etc/apt/sources.list.d/debian-upstream.list, configs-stretch/etc/apt/sources.list.d/stretch-backports.list, debian/changelog
Сборка будет фейлиться, потому что в wbdev сейчас из-за этого же есть проблемы со скачиванием пакетов.
Пакет я собрал локально и положил в репозиторий, проверил на своём контроллере и на процедуре сборки rootfs, на первый взгляд всё хорошо.
=> stretch repos moved to archive.debian.org

configs-stretch/etc/apt/sources.list.d/debian-upstream.list, debian/changelog
@lostpoint-ru был прав, часть пакетов из debian-security не слилась с основным релизом. Нашёл адрес, добавил в список
=> add debian-security from archive to prevent downgrades

configs/etc/udev/rules.d/99-wb-modem.rules, debian/changelog
решили привязать нашему модему специальный тег, чтобы потом дёргать модем по нему
предлагаю тег "wbc"
интересно, что udev имеет доступ к of_compatible и of_name из коробки
проверить можно mmcli -m wbc --set-primary-sim-slot=1
=> udev: add specific tag to WB-internal modems

debian/changelog, debian/wb-configs.postinst
Если до апгрейда на bullseye `/etc/mosquitto/mosquitto.conf` изменялся вручную, то в процессе апгрейда конфиг останется прежним. Сейчас это ожидаемое поведение (`apt-get -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --yes ...`). Учитывая что единственное изменение в mosquitto.conf при апгрейде на bullseye это pid_file, можно хотя бы для части пользователей (тех кто редактировал mosquitto.conf, но не менял pid_file) сделать апгрейд более гладким. Иначе придется в процессе апгрейда спрашивать пользователя, что делать с таким конфигом.
=> mosquitto: fix pid_file path

configs/etc/udev/rules.d/99-wb-modem.rules, debian/changelog
* udev: add specific tag to WB-internal modems
* bump version
* rework udev rule to add simselect_gpio only to compatible modem
* rework simselect gpio
* slight comments changes
* Update debian/changelog
---------
В вики написали, что с 2304 можно делать mmcli -m wbc, а бекпортировать - забыли
=> udev: add specific tag to WB-internal modems (#118)

configs/etc/wb-configs.d/01wb-configs, configs/usr/bin/wb-configs-early, debian/changelog
Before:
```sh
$ ls -l /etc/mosquitto/conf.d
total 0
lrwxrwxrwx 1 root root 54 Jul 20 10:06 00default_listener.conf -> /mnt/data/etc/mosquitto/conf.d/00default_listener.conf
-rw-r--r-- 1 root root  0 Jul 19 18:45 00default_listener.conf.default
lrwxrwxrwx 1 root root 47 Jul 20 10:06 10listeners.conf -> /mnt/data/etc/mosquitto/conf.d/10listeners.conf
lrwxrwxrwx 1 root root 45 Jul 20 10:07 20bridges.conf -> /mnt/data/etc/mosquitto/conf.d/20bridges.conf
-rw-r--r-- 1 root root  0 Jul 19 18:46 30test.conf
$ ls -l /mnt/data/etc/mosquitto/conf.d
total 12
-rw-r--r-- 1 root root 367 Apr 13 16:16 00default_listener.conf
-rw-r--r-- 1 root root 854 Apr 13 16:16 10listeners.conf
-rw-r--r-- 1 root root 163 Jul 12 17:35 20bridges.conf
```
Call `wb_move /etc/mosquitto/conf.d/`:
```sh
$ …
```
=> mosquitto: move /etc/mosquitto/conf.d to /mnt/data

configs/etc/sysctl.d/99-ignore-linkdown.conf, debian/changelog, debian/control
NetworkManager can bring up connections on down links, if the connection has static ip. Depending on metric, the connection can became preferred default route, so all packets go to down link, and connectivity is broken. Add option to ignore routes to down links
Rebase of https://github.com/wirenboard/wb-configs/pull/125
=> Ignore routes to down links

debian/changelog, debian/wb-configs.postrm
Test instructions:
```sh
$ wb-release -t testing
$ /usr/bin/wb-configs-early start
$ ls -la /etc/mosquitto/conf.d
lrwxrwxrwx 1 root root 30 Aug 10 19:30 /etc/mosquitto/conf.d -> /mnt/data/etc/mosquitto/conf.d/
$ ls -la /mnt/data/etc/mosquitto/conf.d
total 56
drwxr-xr-x 2 root root 4096 Aug 10 19:29 ./
drwxr-xr-x 5 root root 4096 Aug  8 09:57 ../
-rw-r--r-- 1 root root  367 Jul 25 16:02 00default_listener.conf
-rw-r--r-- 1 root root  367 Jul 25 16:02 00default_listener.conf.default
-rw-r--r-- 1 root root  367 Aug  4 13:15 00default_listener.conf.dpkg-new
-rw-r--r-- 1 root root  854 Jul 25 16:02 10listeners.conf
-rw-r--r-- 1 root root  854 Jul 25 16:02 10listeners.conf.default
-rw-r--r-- 1 root root  854 Aug  4 13:15 10listeners.conf.dpkg-new
-rw-r--r-- 1 root root  121 Jul 25 16:02 …
```
=> Restore /etc/mosquitto/conf.d folder in .postrm

configs/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf, debian/changelog
this time for real, I promise.
So agetty will switch between list of baudrates when getting BREAK condition. This behaviour causes all sorts of problems because a) it can never go back to higher baudrate
b) BREAK condition can also be caused by noise/power-on and reset glitches and other stuff besides user typing at lower baudrate
We tried to fix it by removing the list of baudrate to iterate. But unfortunately apparently agetty iterprets ''--keep-baud' as list of current baudrate (115200, set by u-boot) and 9600. It's somehow suggested by the man agetty:
"and if unsuccessful then default to '9600'."
So tihs time we set baudrate to 115200, period.
We verified that it inteed prevents agetty from switching to 9600.
=> don't allow serial terminal to change baudrate to 9600

configs/etc/modprobe.d/8733bu.conf, configs/lib/systemd/network/50-wb-wifi-usb.link, debian/changelog
Сделал наименование интерфейсов как в rt8723 и убрал ненужные сообщения из dmesg.
=> Support RTL8733BU

configs/usr/bin/wb-configs-early, debian/changelog
При обновлении фитом старая версия затирала все конфиги, т.к. симлинков не было.
Насколько я понимаю, вся эта машинерия нужна только в случае обновления со старой схемы (раньше были симлинки на конкретные файлы конфига москиты) на бэкап всего каталога.
Сделал так, чтобы всё работало только для каталогов и копировало только недостающие файлы.
=> Fix configs overwriting after update using fit

configs/etc/ssl/openssl.cnf.wb, debian/changelog, debian/wb-configs.displace, debian/wb-configs.postinst
Нужно для работы https://github.com/wirenboard/wb-cloud-agent/
Конфиг OpenSSL взял по умолчанию из bullseye, добавил к нему несколько секций для работы с atecc по этой инструкции: https://wirenboard.com/wiki/CryptodevATECCx08_Auth
=> add openssl config with atecc engine description + nginx access to atecc

configs/usr/lib/cgi-bin/fwupdate_upload.py, debian/changelog
Запрет прошивки контроллера из облака fit-ом без предустановленного wb-cloud-agent
связанных PR-ов - куча => проще всего потыкать:
обновиться из тестинг-сета http://deb.wirenboard.com/all@experimental.update-from-cloud:main
ребут
подключить к облаку
обновиться из облака stable-ом; увидеть ругательства
обновиться fit-ом [с поддержкой обновления из облака](https://jenkins.wirenboard.com/job/pipelines/job/build-image/6241/); не увидеть ругательства
=> fwupdate_upload: handle update from cloud

configs/etc/mosquitto/conf.d/10listeners.conf, debian/changelog, debian/control, debian/wb-configs.postinst
Тестинг-сет: `deb http://deb.wirenboard.com/all experimental.get-rid-of-18883 main`
Часть более крупной задачи -- отключение публичного порта 18883 и перевод homeui на работу с штатным nginx, который проксирует в локальный 18883 порт.
По этому PR критерий успеха -- чтобы порт 18883, который слушает mosquitto, сменился с :::18883 на 127.0.0.1:18883. 
При этом, если не ставить ответную версию homeui из тестинг-сета -- homeui сломается (отвалится от mqtt) до смены порта на 80-й в настройках webui. Если ставить тестинг-сет целиком -- всё должно работать штатно.
=> Mosquitto: disable 18883 public websockets port

configs/etc/nginx/sites-available/default.wb, debian/changelog
Follow up https://github.com/wirenboard/wb-configs/pull/163
```sh
...
Jul 11 17:54:31 wirenboard-A7PWH4NX nginx[1487]: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/default:32
Jul 11 17:54:33 wirenboard-A7PWH4NX nginx[1766]: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/default:32
...
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/default:32
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
https://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types:
> Enables gzipping of responses for the specified MIME types **in addition to “text/html”**. The special value “*” matches any MIME type (0.8.29). **Responses with the …
=> nginx: fix config warning

configs/etc/watchdog.d/10wb-check-emmc, configs/usr/share/wb-configs/watchdog.d/10wb-check-emmc, debian/changelog
Попробовал имитировать отвал emmc через fault injection в ядре, в итоге такой вариант оказался стабильно работающим. Экспериментально проверил, что после отвала emmc может произойти следующее:
1. скрипт и dd остались в кэше - тогда получается код возврата 255 и watchdog перезагружает контроллер сразу.
2. скрипт остался в кэше, но его выполнение вызывает i/o error - получается код возврата 126, тогда watchdog будет пытаться выполнить его ещё 30 секунд.
3. скрипт выпадает из кэша и попытка его вызвать вызывает i/o error - получается код возврата 5, watchdog продолжает пытаться его вызвать.
4. проходит 30 секунд попыток, watchdog пытается вызвать скрипт с аргументом `repair` и у него ничего не получается из-за i/o error - после этого контроллер перезагружается жёстко.
Скрипт поселил в /usr, …
=> try watchdog service script to check emmc health

configs/etc/watchdog.d/10wb-check-emmc, configs/usr/share/wb-configs/watchdog.d/10wb-check-emmc, debian/changelog
#168 нормально работает на wb8, не ожидаю проблем на wb7 и остальных контроллерах, пусть это живёт в тестинге.
=> add watchdog service script to check emmc health

configs/etc/wb-configs.d/04nginx-fix, configs/usr/lib/wb-configs/fix_nginx.sh, debian/changelog
Нужно в частности для удаления `/etc/nginx/sites-enabled/wb-cloud-agent`, который остается от wb-cloud-agent 1.0.0 при обновлении фитом.
=> nginx: check for broken symlinks in /etc/nginx/sites-enabled

configs/etc/apt/sources.list.d/nodesource.list, debian/changelog
Актуальные дебки ноды будут в нашей репе. Можно не бекпортить в стейбл, все равно nodejs в нашей репе свежее и будет браться от туда.
=> remove nodesource

configs/etc/systemd/system/fcgiwrap.service.d/override.conf, debian/changelog
Добавление пользователя в группу mosquitto (необходимо для сообщения о уязвимости wb-cloud-agent в веб-интерфейсе).
=>  Добавление пользователя в группу mosquitto

configs/usr/share/wb-configs/mosquitto/000persistence.conf, debian/changelog, debian/wb-configs.postinst
Решили, что в этом тестинге будем выключать persistence в mosquitto по умолчанию. Обычно это доставляет больше проблем, чем приносит пользы.
Побочные эффекты нам ещё предстоит узнать, разумеется, потому сейчас это уходит в testing.
=> disable persistence in mosquitto by default

configs/etc/update-motd.d/30-wirenboard-ipaddrs, debian/changelog
от инженеров прилетела хотелка: ip езернетов на логинскрине
у меня под рукой нормальных интернетов нет, поэтому картинка про lo и dbg0
стоит ли другие интерфейсы добавлять - хз; я б не добавлял пока
=> add eth0 & eth1 ip addrs to motd

configs/etc/default/locale, debian/changelog
Прописал системуную локаль по-умолчанию в en_US.UTF8, чтобы с SSH-клиентов под windows корректно отображалась псевдографика.
=> Установил системную локаль по-умолчанию в en_US.UTF8

configs/etc/nginx/sites-available/default.wb
Добавил установку значений переменных по умолчанию. Эти переменные используются при формировании заголовка запроса авторизации. Они задают требуемые права доступа, соответствие которым проверяется в запросе авторизации
=> Set default requirements for auth check

configs/etc/NetworkManager/dnsmasq-shared.d/no-default-route.conf, debian/changelog
DHCP-сервер не будет передавать дефолтный маршрут по этому интерфейсу
=> Disable default route on dbg0

debian/changelog, debian/wb-configs.postinst
___________________________________
**Что происходит; кому и зачем нужно:**
```
Mar 03 15:03:36 wirenboard-AC4U5OVN mosquitto[1259575]: 1741014216: Warning: File /etc/mosquitto/acl/default.conf owner is not mosquitto. Future versions will refuse to load this file.To fix this, use `chown mosquitto /etc/mosquitto/acl/default.conf`.
Mar 03 15:03:36 wirenboard-AC4U5OVN mosquitto[1259575]: 1741014216: Warning: File /etc/mosquitto/acl/default.conf group is not mosquitto. Future versions will refuse to load this file.
Mar 03 15:03:36 wirenboard-AC4U5OVN mosquitto[1259575]: 1741014216: Warning: File /etc/mosquitto/acl/default.conf has world readable permissions. Future versions will refuse to load this file.
To fix this, use `chmod 0700 /etc/mosquitto/acl/default.conf`.
```
Москито ругается на …
=> Fix mosquitto acl and password file permissions

configs/etc/wb-prepare.d/01udev-rules, debian/changelog
___________________________________
**Что происходит; кому и зачем нужно:**
Проблема: udev-правила (expose uart pins) не работают при firstboot. Такое же - со всеми правилами, работающими в рантайме (что-то делаем через хвконф); правила при загрузке (например, переименование езернетов) работали и так.
Подебажил - udev все видит => гипотеза - надо дернуть перезагрузку правил. Гипотеза подтвердилась экспериментом: прошили -> firstboot -> убедились, что не работает -> reboot -> убедились, что работает.
Причина:
[не так давно](https://github.com/wirenboard/wb-configs/pull/175) мы перетащили udev-правила в рантайм => правила не перезагружаются после подмены
___________________________________
**Что поменялось для пользователей:**
ничего; пользователям уезжали вб, перезагружавшиеся уже минимум …
=> fix udev rules triggering at firstboot

configs/usr/lib/wb-configs/fix_mosquitto.sh, debian/changelog, debian/wb-configs.postinst
___________________________________
**Что происходит; кому и зачем нужно:**
При обновлении фитом не применяются фиксы конфигов москиты. Затрагивает эти 6 фиксов:
* https://github.com/wirenboard/wb-configs/pull/89 (3.18.1, wb-2310)
* https://github.com/wirenboard/wb-configs/pull/122 (3.18.3, wb-2310)
* https://github.com/wirenboard/wb-configs/pull/148 (3.22.0, wb-2401)
* https://github.com/wirenboard/wb-configs/pull/165 (3.26.5, wb-2407)
* https://github.com/wirenboard/wb-configs/pull/176 (3.34.0, wb-2501)
* https://github.com/wirenboard/wb-configs/pull/204 (3.38.1, wb-2504)
Могло затрагивать пользователей, которые ни разу не обновлялись аптом, а только фитами.
Также wb-configs может при обновлении аптом обновится до mosquitto и тогда фиксы из postinst тоже не применятся. С этим же фиксом …
=> Fix mosquitto configs from wb-configs-early.service

configs/etc/apt/preferences.d/50backports, configs/etc/apt/sources.list.d/debian-upstream.list, debian/changelog
___________________________________
**Что происходит; кому и зачем нужно:**
Backport https://github.com/wirenboard/wb-configs/pull/211
___________________________________
**Что поменялось для пользователей:**
___________________________________
**Как проверял/а:**
=> Remove bullseye-backports apt source (#211)
