configs/etc/apt/sources.list.d/contactless.list, debian/changelog
This should be resolved by apt-get automatically
=> Remove hardcoded architecture from apt repository

configs/etc/network/interfaces.wb, debian/changelog, debian/control
Выставление MAC на интерфейсе перенесено в отдельный скрипт в wb-utils
=> network: use wb-set-mac in pre-up

debian/changelog, debian/wb-configs.init
Signed-off-by: Nikita webconn Maslov <wkernelteam@gmail.com>
=> fix: prevent format data partition on hard resets

configs/etc/wb-configs.d/01wb-configs, debian/changelog, debian/control
=> Fix configs links creation

configs/etc/udev/rules.d/99-wb-i2c.rules, debian/changelog
=> added udev rule for symlink to i2c-mod4

configs/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf, debian/changelog
=> don't change baudrate in serial console

configs/etc/NetworkManager/system-connections/wb-ap.nmconnection, configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh, debian/changelog, debian/control, debian/wb-configs.postinst
Depends on https://github.com/wirenboard/wb-utils/pull/69
=> postinst: fix NetworkManager wb-ap SSID

configs/etc/update-motd.d/20-wirenboard-sysinfo, debian/changelog
rebase https://github.com/wirenboard/wb-configs/pull/82
=> Print load average as system load

configs/etc/apt/preferences.d/40wb-experimental, configs/etc/update-motd.d/10-wirenboard, debian/changelog
- add APT pin for experimental repos
- show experimental repos in the banner
=> Testing sets support

configs/usr/lib/NetworkManager/system-connections/wb-ap.nmconnection, configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh, debian/changelog
=> set Wi-Fi AP channel to 1 explicitly (#110)

configs/usr/lib/systemd/ntp-units.d/10-ntp.list, debian/changelog
Backport of https://github.com/wirenboard/wb-configs/pull/116 to wb-2304
=> Make timedatectl aware of ntp.service

configs/etc/fstab.wb, debian/changelog, debian/wb-configs.postinst
Добавлены в файл и скрипт postinst
=> Add discard noatime mmc options

configs/etc/sudoers.d/www-data, debian/changelog
Проблема из чата тыжпрограммиста - у Андрея Радионова не нашлись пути к утилитам через /usr/bin/
=> Ad /bin/ path to tar, mount and umount

debian/changelog, debian/wb-configs.postinst
=> mosquitto: fix pid_file path

debian/changelog, debian/wb-configs.postinst
=> Fix .postinst exit status

configs/etc/systemd/system/fcgiwrap.service.d/override.conf, debian/changelog
Prefork 2 fcgiwrap processes
По умолчанию, fcgiwrap обрабатывает только 1 запрос. Если заливать fit и ещё что-то сделать, то второй запрос будет ждать окончания заливки фита
=> Add fcgiwrap override

configs/usr/lib/wb-configs/fix_nm_ap_ssid.sh, debian/changelog
Убираю настройки канала и диапазона частот, если это не старый Wi-Fi чип
=> Fix Wi-Fi access point configuration with RTL8733BU

configs/etc/nginx/sites-available/default.wb, configs/usr/lib/cgi-bin/download_configs.sh, configs/usr/lib/cgi-bin/download_everything.sh, debian/changelog
тестинг-сет: deb http://deb.wirenboard.com/all experimental.download-configs-everything main
=> add download configs and download everything buttons backend

configs/etc/wb-security.conf, debian/changelog
Запятая лишняя в конфиг-файле.
=> fix wb_security.conf

configs/etc/nginx/sites-available/default.wb, debian/changelog
Добавил сжатие gzip в настройках ngxin, ужимает статические js/css/etc в разы, клиенты с проблемными каналами доступа будут рады.
=> Enable Nginx gzip compression

configs/etc/systemd/system/mosquitto.service.d/override.conf, configs/usr/lib/cgi-bin/check.sh, debian/changelog, debian/wb-configs.postinst
Backport of https://github.com/wirenboard/wb-configs/pull/169
=> Use mosquitto unix socket in ports checking script (#169)

configs/usr/share/wb-configs/udev/99-wb-uart.rules.wb85x, debian/changelog, debian/wb-configs.postinst
в WB85 решили поменять местами модульки; знает Макс
=> add wb-uart udev rules for wb85x

debian/changelog, debian/wb-configs.maintscript
Follow up #177. Это же conffile, его не достаточно просто удалить из пакета.
=> Fix removing nodesource

configs/usr/lib/cgi-bin/check.sh, debian/changelog
Disable stderr > stdout redirect
=> Fix chech.sh stderr reporting

configs/usr/lib/cgi-bin/check.sh, debian/changelog
Бэкпорт https://github.com/wirenboard/wb-configs/pull/179
=> Minor fix to check.sh error reporting

configs/usr/lib/cgi-bin/factory_reset.py, debian/changelog, debian/control
игрался с immutable-атрибутом на factory-fit -> перетащил логику в [wb-watch-update](https://github.com/wirenboard/wb-utils/pull/162)
=> support factory-fit immutable attr

configs/usr/share/wb-configs/udev/99-wb-uart.rules.wb85x, debian/changelog
забыли сделать симлинки для wb8.5
=> wb85x: ttyWBE0 -> ttyMOD1; ttyWBE1 -> ttyMOD2
